### ISSUE TITLE
could you upload the information for users of v1.0 boards?

### ISSUE THREAD

**Issue by KeLaiFu** [PoloAudiovisual/Quatro#1]
I have a bunch of the older v1 boards, which I built a set of and the module is working great so thanks for that. I wish to send a set of the boards to a friend but the information about the jack modification is no longer available.

Many thanks

*edit* found the same info in the other repository *thumbs*

**Comment by PoloAudiovisual** [comment]
Just uploaded rev1.0 and rev1.1 separately, including the jack mod guide for rev1.0. 
Front panel files are the same for both versions. 

Glad you liked it @KeLaiFu !
